// Tests du Worker v2 : node worker/test/api.test.mjs
import assert from "node:assert/strict";
import worker from "../src/index.js";
import { makeEnv, sent, anthropicCalls } from "./env.mjs";
const lastAnthropic = () => anthropicCalls[anthropicCalls.length - 1];
const JPG = Buffer.from([0xff, 0xd8, 0xff, 0xe0, 0, 16, 74, 70, 73, 70, 0, 1, 1, 0, 0, 1]).toString("base64");
const JPG2 = Buffer.from([0xff, 0xd8, 0xff, 0xe1, 0, 16, 69, 120, 105, 102, 0, 0, 2, 0, 0, 1]).toString("base64");
const PNG = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0, 0, 0, 13, 73, 72, 68, 82]).toString("base64");

const env = await makeEnv();
const ctx = { waitUntil: p => p };
async function call(path, body, { method = "POST", key, ip = "1.1.1.1" } = {}) {
  const headers = { "Content-Type": "application/json", "CF-Connecting-IP": ip };
  if (key) headers.Authorization = "Bearer " + key;
  const res = await worker.fetch(new Request("http://w.test/api/" + path, { method, headers, body: method === "GET" ? undefined : JSON.stringify(body || {}) }), env, ctx);
  return { status: res.status, data: await res.json().catch(() => ({})) };
}
const admin = (action, body = {}) => call("admin", Object.assign({ action }, body), { key: "cle-test" });
let n = 0;
const ok = (cond, msg) => { assert.ok(cond, msg); n++; console.log("  ✓ " + msg); };

console.log("Site existant (format v1)");
let r = await call("auth", { action: "login", code: "ludr-2026-abc" });
ok(r.status === 200 && r.data.planName === "Déchèterie" && r.data.monthlyLimit === 200, "connexion par code, offre Déchèterie (pro) reconnue");
ok(r.data.agents.length === 3, "liste des profils");
r = await call("auth", { action: "register-agent", code: "LUDR-2026-ABC", agent: "Intrus" });
ok(r.status === 400, "plus d'auto-inscription d'un agent avec le seul code");
r = await call("auth", { action: "start-session", code: "LUDR-2026-ABC", agent: "Cyril Guilbert", deviceName: "Android" });
ok(r.status === 200 && r.data.sessionId, "ouverture de session");
const S = { code: "LUDR-2026-ABC", agent: "Cyril Guilbert", sessionId: r.data.sessionId };
ok(r.data.canManageUsers === false, "un agent ne gère pas l'équipe");
r = await call("auth", { action: "start-session", code: "LUDR-2026-ABC", agent: "Cyril Guilbert", deviceName: "iPhone" });
ok(r.status === 409, "session déjà ouverte ailleurs signalée");

r = await call("auth", { action: "login", code: "TRY-OLDTRIAL" });
ok(r.data.memoryEnabled === true, "site v1 gratuit : la mémoire partagée reste active");
r = await call("auth", { action: "login", code: "TRI-RESEAU01" });
ok(r.data.monthlyLimit === 750 && r.data.monthlyRemaining === 350, "client Réseau v1 : quota de 750 scans conservé");
console.log("Sécurité des écritures");
r = await call("memory-set", { code: "LUDR-2026-ABC", brand: "destop", product: "x" });
ok(r.status === 401, "mémoire : écriture refusée sans session");
r = await call("memory-set", Object.assign({ brand: "Destop", product: "Déboucheur liquide", flux: "E", category: "Bases" }, S));
ok(r.status === 200, "mémoire : écriture avec session");
r = await call("memory-set", Object.assign({ brand: "destop", action: "delete" }, S));
ok(r.status === 403, "mémoire : suppression réservée au responsable");
r = await call("product-images", { code: "_GLOBAL", action: "save", item: { productName: "x", url: "https://x" } });
ok(r.status === 403, "photos : écriture globale refusée sans clé admin");
r = await call("product-images", { code: "LUDR-2026-ABC", action: "delete", id: "img1" });
ok(r.status === 401, "photos : suppression refusée sans session");
r = await call("product-images", Object.assign({ action: "save", item: { productName: "White spirit", url: "https://exemple.fr/p.jpg" } }, S));
ok(r.status === 400, "photos : un agent ne peut pas pointer vers une URL externe");
r = await call("product-images", Object.assign({ action: "save", imageData: JPG, imageMime: "image/jpeg", item: { productName: "White spirit", r2Key: "_GLOBAL/img1.jpg" } }, S));
ok(r.status === 200 && r.data.item.addedBy === "Cyril Guilbert" && r.data.item.r2Key.startsWith("img/") && !r.data.item.r2Key.includes("LUDR") && !r.data.item.url.includes("LUDR"), "photos : un agent ajoute une vraie photo, clé opaque sans code de site");
r = await call("product-images", Object.assign({ action: "delete", id: r.data.item.id }, S));
ok(r.status === 403, "photos : un agent ne supprime pas");
r = await call("product-images", Object.assign({ action: "save", imageData: Buffer.from("<svg onload=alert(1)>").toString("base64"), imageMime: "image/svg+xml", item: { productName: "x" } }, S));
ok(r.status === 400, "photos : SVG ou HTML refusés");
r = await call("product-images", Object.assign({ action: "save", imageData: Buffer.from("<html><body>x</body></html>").toString("base64"), imageMime: "image/jpeg", item: { productName: "x" } }, S));
ok(r.status === 400, "photos : faux JPEG refusé (contenu vérifié)");
r = await call("analyze", { code: "LUDR-2026-ABC", image: JPG, prompt: "x" });
ok(r.status === 401, "analyse IA refusée sans session");

console.log("Analyse IA et quotas");
r = await call("analyze", Object.assign({ image: JPG, prompt: "p", system: "s", model: "haiku", mode: "final" }, S));
ok(r.status === 200 && r.data.usage.monthlyUsed === 169, "scan compté (169/200)");
ok(lastAnthropic().system[0].cache_control && lastAnthropic().system[0].text.length > 20000, "consignes métier côté serveur, en cache de prompt");
ok(!JSON.stringify(lastAnthropic()).includes('"s"'), "le prompt système envoyé par le client est ignoré");
ok(/<memoire_site>[^]*- onyx →[^]*<\/memoire_site>/.test(lastAnthropic().messages[0].content[1].text), "mémoire du site ajoutée côté serveur, encadrée comme données");
r = await call("analyze", Object.assign({ image: JPG2, mode: "retry" }, S));
ok(r.status === 409, "seconde passe refusée sur une autre photo");
r = await call("analyze", Object.assign({ image: JPG, prompt: "p", model: "sonnet", mode: "retry" }, S));
ok(r.status === 200 && r.data.usage.monthlyUsed === 169 && lastAnthropic().model.includes("sonnet"), "seconde passe Sonnet non comptée");
r = await call("analyze", Object.assign({ image: JPG, prompt: "p", model: "sonnet", mode: "retry" }, S));
ok(r.status === 409, "pas de seconde passe gratuite à répétition");
// Concurrence : 12 scans lancés en même temps, 5 restants → exactement 5 acceptés, 7 refusés.
await admin("update", { code: "LUDR-2026-ABC", scansOverride: 174 });
const burst = await Promise.all(Array.from({ length: 12 }, () => call("analyze", Object.assign({ image: JPG, mode: "final" }, S))));
const accepted = burst.filter(x => x.status === 200).length, refused = burst.filter(x => x.status === 403).length;
ok(accepted === 5 && refused === 7, `scans simultanés : ${accepted} acceptés, ${refused} refusés, jamais au-delà du quota`);
r = await call("auth", { action: "login", code: "LUDR-2026-ABC" });
ok(r.data.monthlyUsed === 174 && r.data.monthlyRemaining === 0, "compteur exact après la rafale (174/174)");
const retries = await Promise.all(Array.from({ length: 5 }, () => call("analyze", Object.assign({ image: JPG, mode: "retry" }, S))));
ok(retries.filter(x => x.status === 200).length === 1, "une seule seconde lecture gratuite, même en parallèle");
await admin("update", { code: "LUDR-2026-ABC", scansOverride: "" });
r = await call("auth", { action: "login", code: "LUDR-2026-ABC" });
ok(r.data.monthlyLimit === 200 && r.data.monthlyUsed === 174, "quota de l'offre rétabli, consommation conservée");

console.log("Ancien essai gratuit épuisé");
r = await call("auth", { action: "start-session", code: "TRY-OLDTRIAL", agent: "Marc" });
const T = { code: "TRY-OLDTRIAL", agent: "Marc", sessionId: r.data.sessionId };
ok(r.data.planName === "Essai" && r.data.aiEnabled === false, "essai reconnu, scans épuisés");
r = await call("analyze", Object.assign({ image: JPG, prompt: "p" }, T));
ok(r.status === 403 && /pas inclus|Quota/.test(r.data.error), "scan refusé avec un message clair");

console.log("Demande d'accès");
sent.length = 0;
r = await call("request-access", { name: "Paul Petit", email: "PAUL@mairie.fr", organisation: "Mairie de Seichamps", sites: "1", plan: "essentiel", message: "Bonjour" });
ok(r.status === 200 && r.data.id, "demande enregistrée");
ok(sent.length === 1 && sent[0].to[0] === "admin@exemple.fr" && sent[0].reply_to === "paul@mairie.fr", "email à l'admin seulement (pas de relais vers une adresse saisie)");
r = await call("request-access", { name: "Robot", email: "r@x.fr", organisation: "x", website: "spam" });
ok(r.status === 200 && !r.data.id, "champ piège : robot ignoré sans erreur");
for (let i = 0; i < 4; i++) await call("request-access", { name: "A", email: "a@b.fr", organisation: "o" }, { ip: "9.9.9.9" });
r = await call("request-access", { name: "A", email: "a@b.fr", organisation: "o" }, { ip: "9.9.9.9" });
ok(r.status === 200, "5e demande de la même IP acceptée");
r = await call("request-access", { name: "A", email: "a@b.fr", organisation: "o" }, { ip: "9.9.9.9" });
ok(r.status === 429, "6e demande de la même IP bloquée");
for (const p of ["create-trial", "create-checkout"]) { r = await call(p, {}); ok(r.status === 410, p + " fermé (410)"); }

console.log("Administration");
r = await call("admin", { action: "dashboard" }, { key: "mauvaise" });
ok(r.status === 401, "clé admin incorrecte refusée");
r = await admin("dashboard");
ok(r.status === 200 && r.data.requests.length >= 2 && r.data.stats.openRequests >= 2, "tableau de bord avec demandes");
const legacySite = r.data.sites.find(s => s.code === "LUDR-2026-ABC");
ok(legacySite.monthlyUsed === 174 && legacySite.maxAgents === 25, "usage par site, 25 profils max en offre Déchèterie");
ok(legacySite.teamLocked === false && legacySite.trialTotal === legacySite.trialUsed, "site v1 : responsable autonome, pas de scans d'essai en plus sur une offre payante");
sent.length = 0;
r = await admin("create", { site: "Déchèterie de Château-Salins", client: "SIVOM du Saulnois", responsable: "Claire Martin", principalEmail: "c.martin@sivom.fr", agents: ["Luc", "Ana", "luc"], plan: "essentiel", requestId: "REQ-TEST0001", sendEmail: true });
ok(r.status === 200 && /^CHAT-[A-Z0-9]{6}$/.test(r.data.code), "accès créé, code généré : " + r.data.code);
let C = r.data.code;
ok(r.data.email.sent && sent[0].text.includes(C), "email d'accès avec le code");
r = await admin("requests-list");
ok(r.data.items.find(x => x.id === "REQ-TEST0001").status === "convertie", "demande marquée convertie");
r = await call("auth", { action: "login", code: C });
ok(r.data.agents.join(",") === "Claire Martin,Luc,Ana", "responsable et agents créés, sans doublon");
r = await call("auth", { action: "start-session", code: C, agent: "Claire Martin" });
const R = { code: C, agent: "Claire Martin", sessionId: r.data.sessionId };
ok(r.data.agentRole === "responsable" && r.data.canManageUsers === true && !r.data.teamLocked, "le responsable gère son équipe par défaut");
await admin("update", { code: C, teamLocked: true });
r = await call("site-admin", Object.assign({ action: "add-user", name: "Zoé" }, R));
ok(r.status === 403, "site verrouillé par l'admin : le responsable ne peut plus ajouter d'agent");
await admin("update", { code: C, teamLocked: false });
r = await call("site-admin", Object.assign({ action: "add-user", name: "Zoé" }, R));
ok(r.status === 403 && /3 profils/.test(r.data.error), "limite de 3 profils de l'offre Essentiel");
await admin("update", { code: C, agentsOverride: 5 });
r = await call("site-admin", Object.assign({ action: "add-user", name: "Zoé" }, R));
ok(r.status === 200, "limite relevée par l'admin, ajout possible");
r = await call("site-admin", Object.assign({ action: "set-user-role", name: "Luc", role: "responsable" }, R));
r = await call("auth", { action: "login", code: C });
ok(r.status === 200, "transfert du rôle de responsable à Luc");
r = await call("auth", { action: "start-session", code: C, agent: "Luc" });
const L = { code: C, agent: "Luc", sessionId: r.data.sessionId };
ok(r.data.agentRole === "responsable", "Luc est maintenant responsable");
r = await call("site-admin", Object.assign({ action: "access" }, L));
const previousEmail = r.data.recoveryEmail;
sent.length = 0;
r = await call("site-admin", Object.assign({ action: "set-recovery-email", email: "luc@sivom.fr" }, L));
ok(r.status === 200 && r.data.pending === true && r.data.recoveryEmail === previousEmail, "nouvel email de secours : en attente de confirmation, l'ancien reste actif");
ok(sent.some(m => m.to[0] === previousEmail && /Confirmer/.test(m.text)) && sent.some(m => m.to[0] === "admin@exemple.fr"), "lien envoyé à l'ancienne adresse, administration prévenue");
let link = sent.find(m => m.to[0] === previousEmail).text.match(/https?:\/\/\S+\/api\/confirm\?\S+/)[0];
let res = await worker.fetch(new Request(link.replace("https://tridds.com", "http://w.test"), { headers: { "CF-Connecting-IP": "1.1.1.1" } }), env, ctx);
ok(res.status === 200, "le lien de confirmation applique le changement d'email");
r = await call("site-admin", Object.assign({ action: "access" }, L));
ok(r.data.recoveryEmail === "luc@sivom.fr" && !r.data.pending, "email de secours changé après confirmation");
res = await worker.fetch(new Request(link.replace("https://tridds.com", "http://w.test"), { headers: { "CF-Connecting-IP": "1.1.1.1" } }), env, ctx);
ok(res.status === 400, "un lien déjà utilisé ne fonctionne plus");
r = await call("site-admin", Object.assign({ action: "change-code", newCode: "ab" }, L));
ok(r.status === 400, "code trop court refusé");
r = await call("site-admin", Object.assign({ action: "change-code", newCode: "saulnois-2026" }, L));
ok(r.status === 400, "code trop simple (SAULNOIS-2026) refusé");
sent.length = 0;
r = await call("site-admin", Object.assign({ action: "change-code", newCode: "saul-7k2p4f" }, L));
ok(r.status === 200 && r.data.pending === true && !r.data.code, "changement de code : en attente, le nouveau code n'est pas renvoyé");
r = await call("auth", { action: "login", code: C });
ok(r.status === 200, "l'ancien code reste valable tant que rien n'est confirmé");
link = sent.find(m => m.to[0] === "luc@sivom.fr").text.match(/https?:\/\/\S+\/api\/confirm\?\S+/)[0];
res = await worker.fetch(new Request(link.replace("https://tridds.com", "http://w.test"), { headers: { "CF-Connecting-IP": "1.1.1.1" } }), env, ctx);
ok(res.status === 200 && sent.some(m => m.to[0] === "luc@sivom.fr" && /SAUL-7K2P4F/.test(m.text)), "confirmation : code changé et envoyé à l'email de secours");
r = await call("auth", { action: "login", code: C });
ok(r.status === 401, "ancien code refusé après changement par le responsable");
r = await call("auth", { action: "login", code: "SAUL-7K2P4F" });
ok(r.status === 200 && r.data.agents.includes("Luc"), "nouveau code choisi valide, équipe conservée");
r = await call("auth", { action: "start-session", code: "SAUL-7K2P4F", agent: "Luc" });
Object.assign(L, { code: "SAUL-7K2P4F", sessionId: r.data.sessionId });
r = await call("site-admin", Object.assign({ action: "catalog-save", item: { n: "x", x: "y" } }, L));
ok(r.status === 403, "fiches du site réservées à l'offre Déchèterie (site encore en Essentiel)");
const C0 = C; C = "SAUL-7K2P4F";
r = await admin("update", { code: C, plan: "pro", scansOverride: 300 });
ok(r.data.site.monthlyLimit === 300 && r.data.site.planName === "Déchèterie", "changement d'offre et quota spécifique");
r = await call("auth", { action: "heartbeat", code: C, agent: "Luc", sessionId: L.sessionId });
ok(r.status === 401, "changement d'offre : sessions fermées");
r = await admin("regenerate-code", { code: C });
const C2 = r.data.code;
ok(C2 && C2 !== C, "nouveau code généré");
r = await call("auth", { action: "login", code: C });
ok(r.status === 401, "ancien code refusé");
r = await call("auth", { action: "login", code: C2 });
ok(r.status === 200 && r.data.site === "Déchèterie de Château-Salins", "nouveau code valide");
r = await admin("rename-agent", { code: C2, agent: "Ana", newName: "Ana Lopes" });
ok(r.data.site.agentsList.some(a => a.name === "Ana Lopes"), "profil renommé");
r = await admin("update", { code: C2, active: false });
r = await call("auth", { action: "login", code: C2 });
ok(r.status === 401, "accès suspendu : refusé sans révéler que le code existe");

r = await admin("update", { code: "TRI-RESEAU01", scansOverride: "" });
ok(r.data.site.monthlyLimit === 150, "site v1 Réseau : l'admin peut revenir au quota standard (pas écrasé par la migration)");
r = await admin("update", { code: "TRY-OLDTRIAL", plan: "essentiel" });
r = await call("auth", { action: "login", code: "TRY-OLDTRIAL" });
ok(r.data.memoryEnabled === false, "site v1 passé en Essentiel : règles de la nouvelle offre");

console.log("Plafond de profils");
r = await admin("create", { site: "Déchèterie de Toul", responsable: "Max", plan: "pro", agents: Array.from({ length: 24 }, (_, i) => "Agent " + (i + 1)) });
const T2 = r.data.code;
r = await call("auth", { action: "start-session", code: T2, agent: "Max" });
const M = { code: T2, agent: "Max", sessionId: r.data.sessionId };
r = await call("site-admin", Object.assign({ action: "add-user", name: "Encore un" }, M));
ok(r.status === 403 && /25 profils/.test(r.data.error), "26e profil refusé au responsable (25 max)");
await admin("update", { code: T2, agentsOverride: 40 });
r = await call("site-admin", Object.assign({ action: "add-user", name: "Encore un" }, M));
ok(r.status === 200, "plafond relevé par l'admin pour ce site");

console.log("Essai gratuit d'un mois");
r = await admin("create", { site: "Déchèterie de Pompey", responsable: "Nadia", plan: "pro", billing: "essai", paidUntil: "2020-01-31" });
r = await call("auth", { action: "login", code: r.data.code });
ok(r.data.planName === "Essai terminé" && r.data.aiEnabled === false && r.data.monthlyLimit === 0, "essai dépassé : plus d'analyse photo, recherche conservée");
r = await admin("create", { site: "Déchèterie de Frouard", responsable: "Omar", plan: "pro", billing: "essai", paidUntil: "2099-01-31" });
r = await call("auth", { action: "login", code: r.data.code });
ok(r.data.planName === "Essai gratuit" && r.data.aiEnabled === true && r.data.monthlyLimit === 200, "essai en cours : accès complet");
r = await call("request-access", { name: "Léa", email: "lea@mairie.fr", organisation: "Mairie", plan: "pro", trial: true }, { ip: "3.3.3.3" });
r = await admin("requests-list");
ok(r.data.items[0].trial === true, "demande d'essai enregistrée comme telle");

console.log("Photos publiques");
r = await call("public-images", null, { method: "GET" });
ok(r.status === 200 && r.data.items.some(i => i.url.endsWith("/api/img/_GLOBAL/img1.jpg")), "liste publique avec URL R2");
ok(r.data.items.every(i => !/LUDR|SAUL|FROU/.test(i.url) && !("r2Key" in i)), "liste publique : aucun code de site dans les URL");
const sealed = r.data.items.find(i => i.url.includes("/api/i/"));
if (sealed) { res = await worker.fetch(new Request(sealed.url.replace("http://w.test", "http://w.test"), { headers: {} }), env, ctx); ok(res.status === 200, "une ancienne photo (clé avec code) reste servie via son URL chiffrée"); }
res = await worker.fetch(new Request("http://w.test/api/img/LUDR-2026-ABC/x.jpg"), env, ctx);
ok(res.status === 404, "l'ancienne forme d'URL avec le code n'est plus servie");
r = await call("admin-images", { action: "save", code: "_GLOBAL", imageData: PNG, imageMime: "image/png", item: { productName: "Acide Borique", imageFlux: "H" } }, { key: "cle-test" });
ok(r.status === 200 && r.data.item.r2Key.startsWith("_GLOBAL/"), "upload admin vers R2");
r = await call("public-images", null, { method: "GET" });
ok(r.data.items.some(i => i.productName === "Acide Borique"), "cache public vidé après ajout");
r = await admin("images-all");
ok(r.data.items.every(i => i.code), "liste admin des photos avec code du site");

console.log("Essais de codes");
for (let i = 0; i < 20; i++) await call("auth", { action: "login", code: "NOPE-" + i }, { ip: "6.6.6.6" });
r = await call("auth", { action: "login", code: "LUDR-2026-ABC" }, { ip: "6.6.6.6" });
ok(r.status === 429, "20 codes inconnus : adresse IP bloquée un quart d'heure");
r = await call("auth", { action: "login", code: "LUDR-2026-ABC" }, { ip: "7.7.7.7" });
ok(r.status === 200, "les autres adresses ne sont pas touchées");
r = await call("auth", { action: "login", code: "NOPE-1" }, { ip: "8.8.8.8" });
await admin("update", { code: "LUDR-2026-ABC", active: false });
const r2 = await call("auth", { action: "login", code: "LUDR-2026-ABC" }, { ip: "8.8.8.8" });
await admin("update", { code: "LUDR-2026-ABC", active: true });
ok(r.status === 401 && r2.status === 401 && r.data.error === r2.data.error, "code inconnu et accès suspendu : même réponse (pas d'oracle)");
r = await call("site-catalog", { code: "NOPE-2", agent: "x", sessionId: "y" }, { ip: "9.9.9.9" });
const r3 = await call("site-catalog", { code: "LUDR-2026-ABC", agent: "Cyril Guilbert", sessionId: "faux" }, { ip: "9.9.9.9" });
ok(r.status === 401 && r3.status === 401 && r.data.error === r3.data.error, "routes à session : même réponse pour code inconnu et session fausse");
for (let i = 0; i < 20; i++) await call("site-catalog", { code: "NOPE-" + i, agent: "x", sessionId: "y" }, { ip: "9.9.9.9" });
r = await call("site-catalog", { code: "LUDR-2026-ABC", agent: "x", sessionId: "y" }, { ip: "9.9.9.9" });
ok(r.status === 429, "les routes à session comptent aussi dans la limite par adresse");
r = await call("memory-get", { code: "LUDR-2026-ABC" }, { ip: "7.7.7.7" });
ok(r.status === 401, "mémoire du site : lecture refusée sans session");
await call("auth", { action: "start-session", code: "LUDR-2026-ABC", agent: "Cyril Guilbert", deviceName: "Android", force: true }, { ip: "7.7.7.7" });
r = await call("auth", { action: "start-session", code: "LUDR-2026-ABC", agent: "Cyril Guilbert", deviceName: "Tablette", sessionId: "jeton-choisi-par-le-client" }, { ip: "7.7.7.7" });
ok(r.status === 409 && !("sessionId" in (r.data.activeSession || {})), "profil déjà connecté : le jeton actif n'est pas divulgué");
r = await call("auth", { action: "start-session", code: "LUDR-2026-ABC", agent: "Cyril Guilbert", deviceName: "Tablette", sessionId: "jeton-choisi-par-le-client", force: true }, { ip: "7.7.7.7" });
ok(r.status === 200 && r.data.sessionId !== "jeton-choisi-par-le-client", "le jeton de session est toujours tiré par le serveur");

console.log("Journal partagé et récapitulatif");
r = await call("auth", { action: "start-session", code: "LUDR-2026-ABC", agent: "Jura Beldor", deviceName: "Tel", force: true }, { ip: "7.7.7.7" });
const J = { code: "LUDR-2026-ABC", agent: "Jura Beldor", sessionId: r.data.sessionId };
const t0 = new Date().toISOString();
r = await call("journal", Object.assign({ action: "sync", items: [
  { op: "add", entry: { id: "e1", t: t0, n: "White spirit", f: "E", x: "Autres DDS liquides", src: "scan", v: "auto", review: false, conf: 60, brand: "onyx", tone: "eco", agent: "Quelqu'un d'autre" } },
  { op: "add", entry: { id: "e2", t: t0, n: "Acide Picrique", f: "H", x: "Ne pas accepter", src: "search", v: "consulted", tone: "int" } },
  { op: "update", id: "e1", patch: { v: "corrected", to: "Substitut de White Spirit", review: true } }
] }, J), { ip: "7.7.7.7" });
ok(r.status === 200 && r.data.synced === 3, "journal : ajouts et correction synchronisés");
r = await call("journal", Object.assign({ action: "list", days: 7 }, J), { ip: "7.7.7.7" });
const e1 = r.data.items.find(e => e.id === "e1");
ok(r.data.items.length === 2 && e1.v === "corrected" && e1.to === "Substitut de White Spirit", "journal : liste du site avec la correction appliquée");
ok(e1.agent === "Jura Beldor", "journal : l'auteur est la session, pas une valeur libre");
r = await call("auth", { action: "start-session", code: "LUDR-2026-ABC", agent: "Cyril Guilbert", deviceName: "Tel2", force: true }, { ip: "7.7.7.7" });
r = await call("journal", { action: "list", code: "LUDR-2026-ABC", agent: "Cyril Guilbert", sessionId: r.data.sessionId }, { ip: "7.7.7.7" });
ok(r.status === 200 && r.data.items.length === 2, "journal : visible par tous les agents du site");
r = await call("journal", { action: "list", code: "LUDR-2026-ABC" }, { ip: "7.7.7.7" });
ok(r.status === 401, "journal : refusé sans session");
r = await call("journal", Object.assign({ action: "stats", month: t0.slice(0, 7) }, J), { ip: "7.7.7.7" });
ok(r.data.stats.total === 2 && r.data.stats.scans === 1 && r.data.stats.corrected === 1 && r.data.stats.refused === 1 && r.data.stats.byAgent["Jura Beldor"] === 2, "journal : statistiques du mois");
sent.length = 0;
r = await admin("send-recaps", { month: t0.slice(0, 7) });
const recap = sent.find(m => /récapitulatif/i.test(m.subject));
ok(r.data.sent >= 1 && recap && recap.to[0] === "yvan@exemple.fr" && /2 produits orientés/.test(recap.text) && /Substitut de White Spirit/.test(recap.html), "récapitulatif mensuel envoyé au responsable avec les chiffres");
r = await admin("journal", { code: "LUDR-2026-ABC", month: t0.slice(0, 7) });
ok(r.data.stats.total === 2 && r.data.items.length === 2, "admin : journal et statistiques d'un site");

console.log(`\n${n} vérifications réussies`);
