// Tests du Worker v2 : node worker/test/api.test.mjs
import assert from "node:assert/strict";
import worker from "../src/index.js";
import { makeEnv, sent, anthropicCalls } from "./env.mjs";
const lastAnthropic = () => anthropicCalls[anthropicCalls.length - 1];
const JPG = Buffer.from([0xff, 0xd8, 0xff, 0xe0, 0, 16, 74, 70, 73, 70, 0, 1, 1, 0, 0, 1]).toString("base64");
const JPG2 = Buffer.from([0xff, 0xd8, 0xff, 0xe1, 0, 16, 69, 120, 105, 102, 0, 0, 2, 0, 0, 1]).toString("base64");
const PNG = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0, 0, 0, 13, 73, 72, 68, 82]).toString("base64");

const env = await makeEnv();
const ctx = { waitUntil: p => p };
async function call(path, body, { method = "POST", key, ip = "1.1.1.1" } = {}) {
  const headers = { "Content-Type": "application/json", "CF-Connecting-IP": ip };
  if (key) headers.Authorization = "Bearer " + key;
  const res = await worker.fetch(new Request("http://w.test/api/" + path, { method, headers, body: method === "GET" ? undefined : JSON.stringify(body || {}) }), env, ctx);
  return { status: res.status, data: await res.json().catch(() => ({})) };
}
const admin = (action, body = {}) => call("admin", Object.assign({ action }, body), { key: "cle-test" });
let n = 0;
const ok = (cond, msg) => { assert.ok(cond, msg); n++; console.log("  ✓ " + msg); };

console.log("Site existant (format v1)");
let r = await call("auth", { action: "login", code: "ludr-2026-abc" });
ok(r.status === 200 && r.data.planName === "Déchèterie" && r.data.monthlyLimit === 200, "connexion par code, offre Déchèterie (pro) reconnue");
ok(r.data.agents.length === 3, "liste des profils");
r = await call("auth", { action: "register-agent", code: "LUDR-2026-ABC", agent: "Intrus" });
ok(r.status === 400, "plus d'auto-inscription d'un agent avec le seul code");
r = await call("auth", { action: "start-session", code: "LUDR-2026-ABC", agent: "Cyril Guilbert", deviceName: "Android" });
ok(r.status === 200 && r.data.sessionId, "ouverture de session");
const S = { code: "LUDR-2026-ABC", agent: "Cyril Guilbert", sessionId: r.data.sessionId };
ok(r.data.canManageUsers === false, "un agent ne gère pas l'équipe");
r = await call("auth", { action: "start-session", code: "LUDR-2026-ABC", agent: "Cyril Guilbert", deviceName: "iPhone" });
ok(r.status === 409, "session déjà ouverte ailleurs signalée");

r = await call("auth", { action: "login", code: "TRY-OLDTRIAL" });
ok(r.data.memoryEnabled === true, "site v1 gratuit : la mémoire partagée reste active");
r = await call("auth", { action: "login", code: "TRI-RESEAU01" });
ok(r.data.monthlyLimit === 750 && r.data.monthlyRemaining === 350, "client Réseau v1 : quota de 750 scans conservé");
console.log("Sécurité des écritures");
r = await call("memory-set", { code: "LUDR-2026-ABC", brand: "destop", product: "x" });
ok(r.status === 401, "mémoire : écriture refusée sans session");
r = await call("memory-set", Object.assign({ brand: "Destop", product: "Déboucheur liquide", flux: "E", category: "Bases" }, S));
ok(r.status === 200, "mémoire : écriture avec session");
r = await call("memory-set", Object.assign({ brand: "destop", action: "delete" }, S));
ok(r.status === 403, "mémoire : suppression réservée au responsable");
r = await call("product-images", { code: "_GLOBAL", action: "save", item: { productName: "x", url: "https://x" } });
ok(r.status === 403, "photos : écriture globale refusée sans clé admin");
r = await call("product-images", { code: "LUDR-2026-ABC", action: "delete", id: "img1" });
ok(r.status === 401, "photos : suppression refusée sans session");
r = await call("product-images", Object.assign({ action: "save", item: { productName: "White spirit", url: "https://exemple.fr/p.jpg" } }, S));
ok(r.status === 400, "photos : un agent ne peut pas pointer vers une URL externe");
r = await call("product-images", Object.assign({ action: "save", imageData: JPG, imageMime: "image/jpeg", item: { productName: "White spirit", r2Key: "_GLOBAL/img1.jpg" } }, S));
ok(r.status === 200 && r.data.item.addedBy === "Cyril Guilbert" && r.data.item.r2Key.startsWith("LUDR-2026-ABC/"), "photos : un agent ajoute une vraie photo, rangée sous son site");
r = await call("product-images", Object.assign({ action: "delete", id: r.data.item.id }, S));
ok(r.status === 403, "photos : un agent ne supprime pas");
r = await call("product-images", Object.assign({ action: "save", imageData: Buffer.from("<svg onload=alert(1)>").toString("base64"), imageMime: "image/svg+xml", item: { productName: "x" } }, S));
ok(r.status === 400, "photos : SVG ou HTML refusés");
r = await call("product-images", Object.assign({ action: "save", imageData: Buffer.from("<html><body>x</body></html>").toString("base64"), imageMime: "image/jpeg", item: { productName: "x" } }, S));
ok(r.status === 400, "photos : faux JPEG refusé (contenu vérifié)");
r = await call("analyze", { code: "LUDR-2026-ABC", image: JPG, prompt: "x" });
ok(r.status === 401, "analyse IA refusée sans session");

console.log("Analyse IA et quotas");
r = await call("analyze", Object.assign({ image: JPG, prompt: "p", system: "s", model: "haiku", mode: "final" }, S));
ok(r.status === 200 && r.data.usage.monthlyUsed === 169, "scan compté (169/200)");
ok(lastAnthropic().system[0].cache_control && lastAnthropic().system[0].text.length > 20000, "consignes métier côté serveur, en cache de prompt");
ok(!JSON.stringify(lastAnthropic()).includes('"s"'), "le prompt système envoyé par le client est ignoré");
ok(lastAnthropic().messages[0].content[1].text.includes('"onyx"'), "mémoire du site ajoutée côté serveur");
r = await call("analyze", Object.assign({ image: JPG2, mode: "retry" }, S));
ok(r.status === 409, "seconde passe refusée sur une autre photo");
r = await call("analyze", Object.assign({ image: JPG, prompt: "p", model: "sonnet", mode: "retry" }, S));
ok(r.status === 200 && r.data.usage.monthlyUsed === 169 && lastAnthropic().model.includes("sonnet"), "seconde passe Sonnet non comptée");
r = await call("analyze", Object.assign({ image: JPG, prompt: "p", model: "sonnet", mode: "retry" }, S));
ok(r.status === 409, "pas de seconde passe gratuite à répétition");

console.log("Ancien essai gratuit épuisé");
r = await call("auth", { action: "start-session", code: "TRY-OLDTRIAL", agent: "Marc" });
const T = { code: "TRY-OLDTRIAL", agent: "Marc", sessionId: r.data.sessionId };
ok(r.data.planName === "Essai" && r.data.aiEnabled === false, "essai reconnu, scans épuisés");
r = await call("analyze", Object.assign({ image: JPG, prompt: "p" }, T));
ok(r.status === 403 && /pas inclus|Quota/.test(r.data.error), "scan refusé avec un message clair");

console.log("Demande d'accès");
sent.length = 0;
r = await call("request-access", { name: "Paul Petit", email: "PAUL@mairie.fr", organisation: "Mairie de Seichamps", sites: "1", plan: "essentiel", message: "Bonjour" });
ok(r.status === 200 && r.data.id, "demande enregistrée");
ok(sent.length === 1 && sent[0].to[0] === "admin@exemple.fr" && sent[0].reply_to === "paul@mairie.fr", "email à l'admin seulement (pas de relais vers une adresse saisie)");
r = await call("request-access", { name: "Robot", email: "r@x.fr", organisation: "x", website: "spam" });
ok(r.status === 200 && !r.data.id, "champ piège : robot ignoré sans erreur");
for (let i = 0; i < 4; i++) await call("request-access", { name: "A", email: "a@b.fr", organisation: "o" }, { ip: "9.9.9.9" });
r = await call("request-access", { name: "A", email: "a@b.fr", organisation: "o" }, { ip: "9.9.9.9" });
ok(r.status === 200, "5e demande de la même IP acceptée");
r = await call("request-access", { name: "A", email: "a@b.fr", organisation: "o" }, { ip: "9.9.9.9" });
ok(r.status === 429, "6e demande de la même IP bloquée");
for (const p of ["create-trial", "create-checkout"]) { r = await call(p, {}); ok(r.status === 410, p + " fermé (410)"); }

console.log("Administration");
r = await call("admin", { action: "dashboard" }, { key: "mauvaise" });
ok(r.status === 401, "clé admin incorrecte refusée");
r = await admin("dashboard");
ok(r.status === 200 && r.data.requests.length >= 2 && r.data.stats.openRequests >= 2, "tableau de bord avec demandes");
const legacySite = r.data.sites.find(s => s.code === "LUDR-2026-ABC");
ok(legacySite.monthlyUsed === 169 && legacySite.maxAgents === null, "usage par site, agents illimités en offre Déchèterie");
ok(legacySite.teamLocked === true && legacySite.trialTotal === legacySite.trialUsed, "site v1 : équipe verrouillée, pas de scans d'essai en plus sur une offre payante");
sent.length = 0;
r = await admin("create", { site: "Déchèterie de Château-Salins", client: "SIVOM du Saulnois", responsable: "Claire Martin", principalEmail: "c.martin@sivom.fr", agents: ["Luc", "Ana", "luc"], plan: "essentiel", requestId: "REQ-TEST0001", sendEmail: true });
ok(r.status === 200 && /^CHAT-[A-Z0-9]{6}$/.test(r.data.code), "accès créé, code généré : " + r.data.code);
const C = r.data.code;
ok(r.data.email.sent && sent[0].text.includes(C), "email d'accès avec le code");
r = await admin("requests-list");
ok(r.data.items.find(x => x.id === "REQ-TEST0001").status === "convertie", "demande marquée convertie");
r = await call("auth", { action: "login", code: C });
ok(r.data.agents.join(",") === "Claire Martin,Luc,Ana", "responsable et agents créés, sans doublon");
r = await call("auth", { action: "start-session", code: C, agent: "Claire Martin" });
const R = { code: C, agent: "Claire Martin", sessionId: r.data.sessionId };
ok(r.data.agentRole === "responsable" && r.data.canManageUsers === false && r.data.teamLocked, "équipe verrouillée par défaut");
r = await call("site-admin", Object.assign({ action: "add-user", name: "Zoé" }, R));
ok(r.status === 403, "le responsable ne peut pas ajouter d'agent si l'équipe est verrouillée");
await admin("update", { code: C, teamLocked: false });
r = await call("site-admin", Object.assign({ action: "add-user", name: "Zoé" }, R));
ok(r.status === 403 && /3 profils/.test(r.data.error), "limite de 3 profils de l'offre Essentiel");
await admin("update", { code: C, agentsOverride: 5 });
r = await call("site-admin", Object.assign({ action: "add-user", name: "Zoé" }, R));
ok(r.status === 200, "limite relevée par l'admin, ajout possible");
r = await call("site-admin", Object.assign({ action: "catalog-save", item: { n: "x", x: "y" } }, R));
ok(r.status === 403, "fiches du site réservées à l'offre Pro");
r = await admin("update", { code: C, plan: "pro", scansOverride: 300 });
ok(r.data.site.monthlyLimit === 300 && r.data.site.planName === "Déchèterie", "changement d'offre et quota spécifique");
r = await call("auth", { action: "heartbeat", code: C, agent: "Claire Martin", sessionId: R.sessionId });
ok(r.status === 401, "changement d'offre : sessions fermées");
r = await admin("regenerate-code", { code: C });
const C2 = r.data.code;
ok(C2 && C2 !== C, "nouveau code généré");
r = await call("auth", { action: "login", code: C });
ok(r.status === 401, "ancien code refusé");
r = await call("auth", { action: "login", code: C2 });
ok(r.status === 200 && r.data.site === "Déchèterie de Château-Salins", "nouveau code valide");
r = await admin("rename-agent", { code: C2, agent: "Ana", newName: "Ana Lopes" });
ok(r.data.site.agentsList.some(a => a.name === "Ana Lopes"), "profil renommé");
r = await admin("update", { code: C2, active: false });
r = await call("auth", { action: "login", code: C2 });
ok(r.status === 403, "accès suspendu");

r = await admin("update", { code: "TRI-RESEAU01", scansOverride: "" });
ok(r.data.site.monthlyLimit === 150, "site v1 Réseau : l'admin peut revenir au quota standard (pas écrasé par la migration)");
r = await admin("update", { code: "TRY-OLDTRIAL", plan: "essentiel" });
r = await call("auth", { action: "login", code: "TRY-OLDTRIAL" });
ok(r.data.memoryEnabled === false, "site v1 passé en Essentiel : règles de la nouvelle offre");

console.log("Essai gratuit d'un mois");
r = await admin("create", { site: "Déchèterie de Pompey", responsable: "Nadia", plan: "pro", billing: "essai", paidUntil: "2020-01-31" });
r = await call("auth", { action: "login", code: r.data.code });
ok(r.data.planName === "Essai terminé" && r.data.aiEnabled === false && r.data.monthlyLimit === 0, "essai dépassé : plus d'analyse photo, recherche conservée");
r = await admin("create", { site: "Déchèterie de Frouard", responsable: "Omar", plan: "pro", billing: "essai", paidUntil: "2099-01-31" });
r = await call("auth", { action: "login", code: r.data.code });
ok(r.data.planName === "Essai gratuit" && r.data.aiEnabled === true && r.data.monthlyLimit === 200, "essai en cours : accès complet");
r = await call("request-access", { name: "Léa", email: "lea@mairie.fr", organisation: "Mairie", plan: "pro", trial: true }, { ip: "3.3.3.3" });
r = await admin("requests-list");
ok(r.data.items[0].trial === true, "demande d'essai enregistrée comme telle");

console.log("Photos publiques");
r = await call("public-images", null, { method: "GET" });
ok(r.status === 200 && r.data.items.some(i => i.url.endsWith("/api/img/_GLOBAL/img1.jpg")), "liste publique avec URL R2");
r = await call("admin-images", { action: "save", code: "_GLOBAL", imageData: PNG, imageMime: "image/png", item: { productName: "Acide Borique", imageFlux: "H" } }, { key: "cle-test" });
ok(r.status === 200 && r.data.item.r2Key.startsWith("_GLOBAL/"), "upload admin vers R2");
r = await call("public-images", null, { method: "GET" });
ok(r.data.items.some(i => i.productName === "Acide Borique"), "cache public vidé après ajout");
r = await admin("images-all");
ok(r.data.items.every(i => i.code), "liste admin des photos avec code du site");

console.log("Essais de codes");
for (let i = 0; i < 20; i++) await call("auth", { action: "login", code: "NOPE-" + i }, { ip: "6.6.6.6" });
r = await call("auth", { action: "login", code: "LUDR-2026-ABC" }, { ip: "6.6.6.6" });
ok(r.status === 429, "20 codes inconnus : adresse IP bloquée un quart d'heure");
r = await call("auth", { action: "login", code: "LUDR-2026-ABC" }, { ip: "7.7.7.7" });
ok(r.status === 200, "les autres adresses ne sont pas touchées");

console.log(`\n${n} vérifications réussies`);
